/**
 * TourPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TourImportItem } from './tourImportItem';


export interface TourImportRequest { 
    tours: Array<TourImportItem>;
}

