/**
 * TourPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TourExportLogResponse } from './tourExportLogResponse';


export interface TourExportTourResponse { 
    id?: number;
    name?: string | null;
    description?: string | null;
    image?: string | null;
    from?: string | null;
    to?: string | null;
    transportType?: string | null;
    distanceKm?: number;
    estimatedTimeMinutes?: number;
    createdAt?: string;
    logs?: Array<TourExportLogResponse> | null;
}

