/**
 * TourPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TourRoutePointResponse } from './tourRoutePointResponse';


export interface TourPlanResponse { 
    from?: string | null;
    to?: string | null;
    transportType?: string | null;
    distanceKm?: number;
    estimatedTimeMinutes?: number;
    geometry?: Array<TourRoutePointResponse> | null;
    source?: string | null;
}

