/**
 * TourPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TourSearchResponse { 
    id?: number;
    userId?: number;
    name?: string | null;
    description?: string | null;
    image?: string | null;
    from?: string | null;
    to?: string | null;
    transportType?: string | null;
    distanceKm?: number;
    estimatedTimeMinutes?: number;
    createdAt?: string;
    popularity?: number;
    childFriendlinessScore?: number;
    matchSummary?: string | null;
}
