/**
 * TourPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TourExportTourResponse } from './tourExportTourResponse';


export interface TourExportResponse { 
    tours?: Array<TourExportTourResponse> | null;
}

