/**
 * TourPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TourRequest { 
    name: string;
    description?: string | null;
    from?: string | null;
    to?: string | null;
    transportType?: string | null;
    distanceKm?: number;
    estimatedTimeMinutes?: number;
}

