@baseUrl = http://localhost:5000
##################################################


################################################## health
GET {{baseUrl}}/health
#####

################################################## test
GET {{baseUrl}}/test
#####

################################################## Values
GET {{baseUrl}}/Values/Dummy
#####
