using GrueneisR.RestClientGenerator;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Microsoft.OpenApi;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using TourPlanner.Data;
using TourPlanner.Models;
using TourPlanner.Services;

string corsKey = "_myAllowSpecificOrigins";
string swaggerVersion = "v1";
string swaggerTitle = "TourPlanner";
string restClientFolder = Environment.CurrentDirectory;
string restClientFilename = "_requests.http";

var builder = WebApplication.CreateBuilder(args);
string connectionString = builder.Configuration.GetConnectionString("TourPlanner") ?? "Host=localhost;Port=5432;Database=TourPlanner;Username=postgres;Password=postgres";
var jwtSettings = builder.Configuration.GetSection(JwtSettings.SectionName).Get<JwtSettings>() ?? new JwtSettings();

try
{
  using var probe = new NpgsqlConnection(connectionString);
  probe.Open();
}
catch
{
  throw new InvalidOperationException("PostgreSQL database is not reachable.");
}

builder.Services.AddControllers().AddJsonOptions(options =>
{
  options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
});
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddAuthorization();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
  .AddJwtBearer(options =>
  {
    options.TokenValidationParameters = new TokenValidationParameters
    {
      ValidateIssuer = true,
      ValidateAudience = true,
      ValidateLifetime = true,
      ValidateIssuerSigningKey = true,
      ValidIssuer = jwtSettings.Issuer,
      ValidAudience = jwtSettings.Audience,
      IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSettings.Key)),
      ClockSkew = TimeSpan.Zero,
    };
  });
builder.Services.AddSwaggerGen(x => x.SwaggerDoc(
  swaggerVersion,
  new OpenApiInfo { Title = swaggerTitle, Version = swaggerVersion }
));
builder.Services.AddCors(options => options.AddPolicy(
  corsKey,
  x => x.SetIsOriginAllowed(_ => true).AllowAnyMethod().AllowAnyHeader().AllowCredentials()
));
builder.Services.AddDbContext<TourPlannerDbContext>(options => options.UseNpgsql(connectionString));
builder.Services.AddScoped<ITokenService, JwtTokenService>();
builder.Services.AddScoped<IPasswordHasher<AppUser>, PasswordHasher<AppUser>>();
builder.Services.AddRestClientGenerator(options => options
  .SetFolder(restClientFolder)
  .SetFilename(restClientFilename)
  .SetAction($"swagger/{swaggerVersion}/swagger.json")
);

builder.Services.AddLogging(x => x.AddCustomFormatter());

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
  app.UseDeveloperExceptionPage();
  Console.ForegroundColor = ConsoleColor.Green;
  Console.WriteLine($"++++ Swagger enabled: http://localhost:5000");
  app.UseSwagger();
  Console.WriteLine($"++++ RestClient generating (after first request) to {restClientFolder}\\{restClientFilename}");
  app.UseRestClientGenerator();
  app.UseSwaggerUI(x => x.SwaggerEndpoint($"/swagger/{swaggerVersion}/swagger.json", swaggerTitle));
  Console.ResetColor();
}

app.UseCors(corsKey);
app.UseAuthentication();
app.UseAuthorization();
app.Map("/", () => Results.Redirect("/swagger"));
app.MapControllers();
using (var scope = app.Services.CreateScope())
{
  var db = scope.ServiceProvider.GetRequiredService<TourPlannerDbContext>();
  db.Database.EnsureCreated();
  db.Database.ExecuteSqlRaw("""
    CREATE TABLE IF NOT EXISTS "TourLogs" (
      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "TourId" integer NOT NULL REFERENCES "Tours"("Id") ON DELETE CASCADE,
      "LogDateTime" timestamp without time zone NOT NULL,
      "Comment" character varying(2000),
      "Difficulty" character varying(20) NOT NULL,
      "TotalDistanceKm" double precision NOT NULL,
      "TotalTimeMinutes" integer NOT NULL,
      "Rating" integer,
      "CreatedAt" timestamp without time zone NOT NULL
    );
    CREATE INDEX IF NOT EXISTS "IX_TourLogs_TourId" ON "TourLogs" ("TourId");
    """);
}
Console.WriteLine($"Ready for clients at {DateTime.Now:HH:mm:ss} ...");
app.Run();
