using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using TourPlanner.Data;
using TourPlanner.Models;
using TourPlanner.Services;

namespace TourPlanner.Infrastructure;

public static class InfrastructureServiceCollectionExtensions
{
  public static IServiceCollection AddTourPlannerInfrastructure(this IServiceCollection services, IConfiguration configuration)
  {
    var connectionString = configuration.GetConnectionString("TourPlanner");
    if (string.IsNullOrWhiteSpace(connectionString))
    {
      throw new InvalidOperationException("Missing ConnectionStrings:TourPlanner configuration. Set it via dotnet user-secrets.");
    }

    services.Configure<JwtSettings>(configuration.GetSection(JwtSettings.SectionName));
    services.Configure<OpenRouteServiceSettings>(configuration.GetSection(OpenRouteServiceSettings.SectionName));
    services.AddDbContext<TourPlannerDbContext>(options => options.UseNpgsql(connectionString));
    services.AddScoped<ITokenService, JwtTokenService>();
    services.AddScoped<ITourImageStorageService, FileSystemTourImageStorageService>();
    services.AddScoped<IPasswordHasher<AppUser>, PasswordHasher<AppUser>>();
    services.AddHttpClient<IRoutePlanningService, OpenRouteServiceRoutePlanningService>();

    return services;
  }
}

public static class InfrastructureApplicationBuilderExtensions
{
  public static async Task InitializeTourPlannerDatabaseAsync(this IApplicationBuilder app)
  {
    using var scope = app.ApplicationServices.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<TourPlannerDbContext>();
    db.Database.EnsureCreated();
    db.Database.ExecuteSqlRaw("""
      ALTER TABLE IF EXISTS "Tours"
        ADD COLUMN IF NOT EXISTS "Image" character varying(2000);
      ALTER TABLE IF EXISTS "TourLogs"
        ALTER COLUMN "LogDateTime" TYPE timestamp without time zone USING "LogDateTime" AT TIME ZONE 'UTC';
      CREATE TABLE IF NOT EXISTS "TourLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "TourId" integer NOT NULL REFERENCES "Tours"("Id") ON DELETE CASCADE,
        "LogDateTime" timestamp without time zone NOT NULL,
        "Comment" character varying(2000),
        "Difficulty" character varying(20) NOT NULL,
        "TotalDistanceKm" double precision NOT NULL,
        "TotalTimeMinutes" integer NOT NULL,
        "Rating" integer,
        "CreatedAt" timestamp without time zone NOT NULL
      );
      CREATE INDEX IF NOT EXISTS "IX_TourLogs_TourId" ON "TourLogs" ("TourId");
      """);
    await Task.CompletedTask;
  }
}
